### ISSUE TITLE
 Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by N3XPW** [fipso/Twitch-DripDropBot#1]
Beim ausführen der app.js kommt immer ein " Unexpected token u in JSON at position 0" fehler. Bzw vorher "no such file or directory, open './use_twitch.txt'" Das ganze ist aber mit dem erstellen der use_twitch datei "behoben". Danach kommt wie gesagt der unexpected token fehler. Ich denke das ist zurück zu führen auf den Parse der twitch und riot datei. Die es ja noch garnicht gibt bzw ja eh leer ist.

Muss ich vorher noch andere "module" ausführen ?

**Comment by AllsGamingHD** [comment]
Hey, guys,

It works, just do you know how to code? 
If you know how to code, just read the code... and you'll have the solution in less than a minute!

Hint: reading an empty or non-existent file is impossible, or a simple loop problem if the file is good!

It's a big hint ;)

By the way, fispo ? do you have a discord or something to contact you ? :)

**Comment by N3XPW** [comment]
I know tho. Thats what i wrote, that the filles are missing and empty.
By executing the twitch and or riot.js no accounts are created.

**Comment by AllsGamingHD** [comment]
I'm not sure you had any real JS/NodeJS skills...
I'm a beginner in JS/NodeJS, I made all of them work within a few minutes after reading the codes...

Only app.js can be called to open the project (create a twitch, riot, link or watch account)
You need call functions not open twitch.js or another files.

The file is missing or empty it's normal, you have to fill it with the information that the watch() function needs to retrieve.

I rewrote and adapted/added functions in all the project in my own way for my part all works perfectly (I didn't know the puppeteer module before which is great ;-P)

**Comment by fipso** [comment]
Hello guys,
to get this working u need to create the following txt files:

anticaptcha_key.txt  linked_twitch.txt  twitch.txt
linked_riot.txt      riot.txt           use_twitch.txt

Look at the code in the main.js. there are 4 functions: twitch() riot() link() watch()
u can write your own cli script or just change the function u want to use in the main.js file.

Because i am a fucking retard and leaked by anticaptcha API key in the util.js, the key is probably dead now. so if u need automatic captcha solving replace it with your own one. (anticaptcha.com 1k captchas 3-5$)

könnt mich auch gern auf discord adden; fipso100#0051
u can add me on discord aswell: fipso100#0051

**Comment by fipso** [comment]
If the unexpected token error still exists. Please show the full error message.

**Comment by N3XPW** [comment]
@AllsGamingHD would you mind publishing your project as an forked one?
Havent worked with nodejs/js yet and would like to use that script tho.

**Comment by fipso** [comment]
Ah Btw. The `Unexpected token u in JSON at position 0` means that there is something wrong with the cookies in either riot or twitch.txt

**Comment by WaltDisneyWorld** [comment]
Whats your new Discord? Mine is Caleb.#0002

**Comment by fipso** [comment]
fipso100#0420 but if this code is broken i wont fix it, dont have any use for it.
